### ISSUE TITLE
Merge this project into w2ui!

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui-dist#3]
Please merge this project into w2ui the same way Twitter Bootstrap did it too:
https://github.com/twbs/bootstrap/blob/master/bower.json
The only thing required is just to have more "ignores" so that bower downloads only the required stuff.

Few reasons for a "single" project:
 - easier to maintain, single repo, single tracker
 - most other projects do this too now
 - users can reference from bower branches too (not just tags), so they can easily try out before something is released in branches too an have a much more effective feedback.

IMHO point 3 is very important.

**Comment by vitmalina** [comment]
Can you please help me how to define ignore. Ideally, I just wanted stuff in /dist folder, but I do not want it in the folder, but in root. So that in final install it would be

/bower_components/w2ui/w2ui-1.4.2.min.js
/bower_components/w2ui/w2ui-1.4.2.js
/bower_components/w2ui/w2ui-1.4.2.min.css
/bower_components/w2ui/w2ui-1.4.2.css

**Comment by aadrian** [comment]
>  I just wanted stuff in /dist folder, but I do not want it in the folder, but in root.

Unfortunately it is not possible to "map" with the actual version of Bower such a thing :(.

A. This is why most projects (Bootstrap, JQuery, etc) will leave the resources like:

```
/bower_components/w2ui/dist/w2ui-1.4.2.js
```
of course, what's possible is for the using projects to have have a different directory instead of ```/bower_components/```. It can be configured in .bowerrc
```json
{
   "directory": "libs"
}
```
and now will be:
```
/libs/w2ui/dist/w2ui-1.4.2.js
```
This might still seem ugly, but most projects I've encountered will have this only in "development mode". For production mode there's something like the Asset Pipeline that will post-process those resource files.

B. Other projects that have only a few output resources, will place them in the root directory exactly for this reason (Select2, Moment, Underscore,etc.)

**Comment by aadrian** [comment]
see https://github.com/vitmalina/w2ui/pull/961

**Comment by vitmalina** [comment]
I responded to that issue. If there is no better way, I think it will not work.
